## Numpy

In [26]:
#install numpy library windows
!pip install numpy

In [ ]:
#install numpy library linux
!sudo apt-get install numpy

In [ ]:
#install numpy library mac
pip3 install numpy

In [30]:
import numpy as np

In [32]:
np.__version__

'1.26.4'

In [34]:
#Create numpy array --> 1D Arr , 1 row
arr = np.array([1,2,3,4])

In [36]:
arr

array([1, 2, 3, 4])

In [38]:
type(arr)

numpy.ndarray

In [44]:
#Create numpy array --> 2D arr
arr2 = np.array([[1,2,3],[4,5,6]])

In [42]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
#Create numpy array --> 3D arr
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [54]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [58]:
arr4 = np.array([])

In [60]:
arr4

array([], dtype=float64)

In [70]:
#2D , 3 rows, 4 col , float
a = np.zeros((3,4),dtype = float)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
#2D , 3 rows, 4 col , int
a = np.zeros((3,4),dtype = int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [80]:
#1D ,1row, 5 col , int
a = np.zeros(5, dtype = int)
a

array([0, 0, 0, 0, 0])

In [90]:
#3D ,3 arrays,5row,7col , int
a = np.zeros((3,5,7), dtype = int)
a

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

In [94]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [96]:
np.ones((6,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [98]:
np.ones((4,6,3), dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [100]:
np.arange(10,26)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [102]:
np.arange(10,26,5) #start, stop , step

array([10, 15, 20, 25])

In [112]:
np.arange(0,2.5,0.5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [114]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [116]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [118]:
np.full((4),2)

array([2, 2, 2, 2])

In [120]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [122]:
np.full((2,4,3),7)

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]])

In [126]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [128]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [130]:
# create random numbers form 0 : 1
np.random.random((2,2))

array([[0.95941725, 0.09469703],
       [0.57618645, 0.92711508]])

In [132]:
np.random.random((4,6))

array([[0.93539078, 0.26851959, 0.53637142, 0.39991155, 0.66413201,
        0.65807838],
       [0.17029165, 0.45438863, 0.39176724, 0.56697275, 0.03980442,
        0.17450989],
       [0.67035003, 0.29096723, 0.55749988, 0.84202429, 0.47573234,
        0.25877334],
       [0.81643546, 0.89878833, 0.66329307, 0.31088716, 0.56664821,
        0.7409901 ]])

In [136]:
# create random numbers form 0 : 1
np.random.rand(3,2)

array([[0.9184243 , 0.32454323],
       [0.44425911, 0.30464619],
       [0.24534529, 0.54591253]])

In [138]:
# create random numbers in normal dis 
np.random.randn(3,2)

array([[ 1.92303303,  0.61641881],
       [ 1.9122775 , -0.70461295],
       [-1.37010104, -1.60449821]])

In [140]:
np.random.randint(low = 5, high= 50, size = (5,4))

array([[47, 17, 12, 30],
       [40, 28, 47, 11],
       [30, 16,  8, 48],
       [43, 11, 44, 27],
       [21, 22,  9, 13]])

In [142]:
np.empty((3,2))

array([[1.92303303, 0.61641881],
       [1.9122775 , 0.70461295],
       [1.37010104, 1.60449821]])

In [146]:
np.empty((5,6))

array([[1.30185787e-311, 1.01283457e-321, 0.00000000e+000,
        0.00000000e+000, 2.41907520e-312, 1.16097020e-028],
       [8.26440822e-072, 3.17976464e-028, 1.42516662e-071,
        1.04917183e-153, 5.23081515e-143, 2.85372158e-056],
       [3.92875831e-033, 2.22732776e+180, 1.64759679e+185,
        7.49305113e-144, 3.59751658e+252, 1.46901661e+179],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        2.80652127e-032, 3.53305418e-057, 7.48494807e-091],
       [1.10634868e-046, 7.31509113e-042, 5.04621343e+180,
        1.94918963e-153, 1.14484251e+243, 2.59903827e-144]])

In [148]:
np.array([])

array([], dtype=float64)

In [150]:
arr = np.full((3,5),8)

In [152]:
arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [154]:
#(row,column)
arr.shape

(3, 5)

In [156]:
len(arr) # num of rows

3

In [158]:
arr.ndim

2

In [160]:
arr.size

15

In [162]:
arr.dtype

dtype('int32')

In [164]:
arr.dtype.name

'int32'

In [176]:
a = np.array([1,2.4,5.9,3,4])
a

array([1. , 2.4, 5.9, 3. , 4. ])

In [178]:
a.dtype

dtype('float64')

In [180]:
a = a.astype(int)
a

array([1, 2, 5, 3, 4])

In [186]:
#ask for help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [188]:
#ask for help
np.info(np.ndarray.size)

Number of elements in the array.

Equal to ``np.prod(a.shape)``, i.e., the product of the array's
dimensions.

Notes
-----
`a.size` returns a standard arbitrary precision Python integer. This
may not be the case with other methods of obtaining the same value
(like the suggested ``np.prod(a.shape)``, which returns an instance
of ``np.int_``), and may be relevant if the value is used further in
calculations that may overflow a fixed size integer type.

Examples
--------
>>> x = np.zeros((3, 5, 2), dtype=np.complex128)
>>> x.size
30
>>> np.prod(x.shape)
30


In [241]:
#mathematicl operations
a = np.array([1,2,3,4])
b = np.array([5,2,7,8])

In [192]:
a + b 

array([ 6,  8, 10, 12])

In [194]:
np.add(a,b)

array([ 6,  8, 10, 12])

In [196]:
a-b

array([-4, -4, -4, -4])

In [198]:
b-a

array([4, 4, 4, 4])

In [200]:
np.subtract(b,a)

array([4, 4, 4, 4])

In [202]:
b*a

array([ 5, 12, 21, 32])

In [204]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [206]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [208]:
np.divide(b,a)

array([5.        , 3.        , 2.33333333, 2.        ])

In [210]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [212]:
np.sqrt(b)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [214]:
print(np.sin(a))
print(np.cos(b))
print(np.log(a))
print(np.exp(b))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.28366219  0.96017029  0.75390225 -0.14550003]
[0.         0.69314718 1.09861229 1.38629436]
[ 148.4131591   403.42879349 1096.63315843 2980.95798704]


In [216]:
a

array([1, 2, 3, 4])

In [218]:
b

array([5, 6, 7, 8])

In [222]:
5 + 12 + 21+ 32

70

In [224]:
np.dot(a,b)

70

In [243]:
a == b

array([False,  True, False, False])

In [245]:
a

array([1, 2, 3, 4])

In [247]:
a < 4

array([ True,  True,  True, False])

In [249]:
a.sum()

10

In [251]:
a.min()

1

In [253]:
a.max()

4

In [255]:
a  = np.array([[11,10,3,4],[9,6,7,8]])
a

array([[11, 10,  3,  4],
       [ 9,  6,  7,  8]])

In [257]:
a.max()

11

In [259]:
a.shape

(2, 4)

In [261]:
a.max(axis = 1) #rows

array([11,  9])

In [263]:
a.max(axis = 0) #columns

array([11, 10,  7,  8])

In [275]:
arr= np.array([1,7,9,4,10,20])
arr

array([ 1,  7,  9,  4, 10, 20])

In [279]:
arr.cumsum()

array([ 1,  8, 17, 21, 31, 51])

In [303]:
arr

array([ 1,  7,  9,  4, 10, 20])

In [283]:
arr.mean()

8.5

In [285]:
np.median(arr)

8.0

In [287]:
np.std(arr)

5.9651767227244274

In [305]:
arr_veiw = arr.view()
arr_veiw

array([ 1,  7,  9,  4, 10, 20])

In [307]:
arr_veiw

array([ 1,  7,  9,  4, 10, 20])

In [309]:
arr_c = np.copy(arr)

In [311]:
arr_c

array([ 1,  7,  9,  4, 10, 20])

In [313]:
arr.sort()

In [315]:
arr

array([ 1,  4,  7,  9, 10, 20])

In [317]:
arr[0]

1

In [319]:
arr[1:4]

array([4, 7, 9])

In [323]:
arr[::-1]

array([20, 10,  9,  7,  4,  1])

In [325]:
arr[arr<5]

array([1, 4])

In [327]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [329]:
#transposed matrix , rows --> columns , columns-->rows
arr_t = np.transpose(arr)
arr_t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [337]:
arr_t1 = arr.T
arr_t1

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [347]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [349]:
#convert 2D array --> 1D array
arr_1d = np.ravel(arr)
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [343]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [351]:
#convert 3D array --> 1D array
arr3_1d = np.ravel(arr3)
arr3_1d

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [353]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [355]:
new_arr = arr_1d.reshape(2,4)
new_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [357]:
new_arr1 = arr_1d.reshape(4,2)
new_arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [359]:
new_arr1 = arr_1d.reshape(5,3)
new_arr1

ValueError: cannot reshape array of size 8 into shape (5,3)

In [370]:
a = np.array([[9,1],[2,3]])
a

array([[9, 1],
       [2, 3]])

In [372]:
np.resize(a,(3,3))

array([[9, 1, 2],
       [3, 9, 1],
       [2, 3, 9]])

In [374]:
a = np.array([1,2,3,4])
a = np.append(a,(1))
a

array([1, 2, 3, 4, 1])

In [376]:
a = np.append(a,(7,9,10))
a

array([ 1,  2,  3,  4,  1,  7,  9, 10])

In [380]:
a  = np.insert(a,1,20)

In [382]:
a

array([ 1, 20,  2,  3,  4,  1,  7,  9, 10])

In [386]:
a[0] = 40
a

array([40, 20,  2,  3,  4,  1,  7,  9, 10])

In [388]:
a = np.delete(a,[1])
a

array([40,  2,  3,  4,  1,  7,  9, 10])

In [390]:
a = np.delete(a,[0,1])
a

array([ 3,  4,  1,  7,  9, 10])

In [ ]:
'''
create array ---> 1d array (5,)
1- append more than 2 items
2- insert 30 in index 3
3- replace item in index 0 ---> 'hello'
4- delete item in index 2
'''